name: payhere
description: Payhere SDK Plugin for Flutter (Android Only Yet)
version: 0.5.2
repository: https://github.com/SrilalS/Payhere-Flutter-Plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.srilals.payhere
        pluginClass: PayherePlugin
